production:
  adapter: mysql2
  database: rensou 
  host: localhost
  username: root
  password: pass
  encoding: utf8

development:
  adapter: mysql2
  database: rensou-dev 
  host: localhost
  username: root
  password: pass
  encoding: utf8